Traceback (most recent call last):
  File "/Users/yusufdanisman/anaconda3/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/yusufdanisman/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yusufdanisman/anaconda3/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yusufdanisman/anaconda3/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/yusufdanisman/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/yusufdanisman/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/yusufdanisman/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
N = 100
x1_values = np.linspace( min(X_train[:,index_mcp]), max(X_train[:,index_mcp]), N )
x2_values = np.linspace( min(X_train[:,index_wa]), max(X_train[:,index_wa]), N )

x_values = [(x1,x2) for x1 in x1_values for x2 in x2_values]
x1_values = [i[0] for i in x_values]
x2_values = [i[1] for i in x_values]

y_pred = dt.predict(x_values)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[17], line 2[0m
[1;32m      1[0m N [38;5;241m=[39m [38;5;241m100[39m
[0;32m----> 2[0m x1_values [38;5;241m=[39m np[38;5;241m.[39mlinspace( [38;5;28mmin[39m(X_train[:,index_mcp]), [38;5;28mmax[39m(X_train[:,index_mcp]), N )
[1;32m      3[0m x2_values [38;5;241m=[39m np[38;5;241m.[39mlinspace( [38;5;28mmin[39m(X_train[:,index_wa]), [38;5;28mmax[39m(X_train[:,index_wa]), N )
[1;32m      5[0m x_values [38;5;241m=[39m [(x1,x2) [38;5;28;01mfor[39;00m x1 [38;5;129;01min[39;00m x1_values [38;5;28;01mfor[39;00m x2 [38;5;129;01min[39;00m x2_values]

[0;31mNameError[0m: name 'np' is not defined

