Traceback (most recent call last):
  File "/Users/yusufdanisman/anaconda3/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/yusufdanisman/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yusufdanisman/anaconda3/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yusufdanisman/anaconda3/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/yusufdanisman/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/yusufdanisman/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/yusufdanisman/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
rf.predict(cv.transform(['It is really good.']))
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn[32], line 1[0m
[0;32m----> 1[0m rf[38;5;241m.[39mpredict(cv[38;5;241m.[39mtransform([[38;5;124m'[39m[38;5;124mIt is really good.[39m[38;5;124m'[39m]))

File [0;32m~/anaconda3/lib/python3.11/site-packages/sklearn/ensemble/_forest.py:820[0m, in [0;36mForestClassifier.predict[0;34m(self, X)[0m
[1;32m    799[0m [38;5;28;01mdef[39;00m [38;5;21mpredict[39m([38;5;28mself[39m, X):
[1;32m    800[0m [38;5;250m    [39m[38;5;124;03m"""[39;00m
[1;32m    801[0m [38;5;124;03m    Predict class for X.[39;00m
[1;32m    802[0m 
[0;32m   (...)[0m
[1;32m    818[0m [38;5;124;03m        The predicted classes.[39;00m
[1;32m    819[0m [38;5;124;03m    """[39;00m
[0;32m--> 820[0m     proba [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mpredict_proba(X)
[1;32m    822[0m     [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39mn_outputs_ [38;5;241m==[39m [38;5;241m1[39m:
[1;32m    823[0m         [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39mclasses_[38;5;241m.[39mtake(np[38;5;241m.[39margmax(proba, axis[38;5;241m=[39m[38;5;241m1[39m), axis[38;5;241m=[39m[38;5;241m0[39m)

File [0;32m~/anaconda3/lib/python3.11/site-packages/sklearn/ensemble/_forest.py:862[0m, in [0;36mForestClassifier.predict_proba[0;34m(self, X)[0m
[1;32m    860[0m check_is_fitted([38;5;28mself[39m)
[1;32m    861[0m [38;5;66;03m# Check data[39;00m
[0;32m--> 862[0m X [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_validate_X_predict(X)
[1;32m    864[0m [38;5;66;03m# Assign chunk of trees to jobs[39;00m
[1;32m    865[0m n_jobs, _, _ [38;5;241m=[39m _partition_estimators([38;5;28mself[39m[38;5;241m.[39mn_estimators, [38;5;28mself[39m[38;5;241m.[39mn_jobs)

File [0;32m~/anaconda3/lib/python3.11/site-packages/sklearn/ensemble/_forest.py:602[0m, in [0;36mBaseForest._validate_X_predict[0;34m(self, X)[0m
[1;32m    599[0m [38;5;250m[39m[38;5;124;03m"""[39;00m
[1;32m    600[0m [38;5;124;03mValidate X whenever one tries to predict, apply, predict_proba."""[39;00m
[1;32m    601[0m check_is_fitted([38;5;28mself[39m)
[0;32m--> 602[0m X [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_validate_data(X, dtype[38;5;241m=[39mDTYPE, accept_sparse[38;5;241m=[39m[38;5;124m"[39m[38;5;124mcsr[39m[38;5;124m"[39m, reset[38;5;241m=[39m[38;5;28;01mFalse[39;00m)
[1;32m    603[0m [38;5;28;01mif[39;00m issparse(X) [38;5;129;01mand[39;00m (X[38;5;241m.[39mindices[38;5;241m.[39mdtype [38;5;241m!=[39m np[38;5;241m.[39mintc [38;5;129;01mor[39;00m X[38;5;241m.[39mindptr[38;5;241m.[39mdtype [38;5;241m!=[39m np[38;5;241m.[39mintc):
[1;32m    604[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([38;5;124m"[39m[38;5;124mNo support for np.int64 index based sparse matrices[39m[38;5;124m"[39m)

File [0;32m~/anaconda3/lib/python3.11/site-packages/sklearn/base.py:588[0m, in [0;36mBaseEstimator._validate_data[0;34m(self, X, y, reset, validate_separately, **check_params)[0m
[1;32m    585[0m     out [38;5;241m=[39m X, y
[1;32m    587[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m no_val_X [38;5;129;01mand[39;00m check_params[38;5;241m.[39mget([38;5;124m"[39m[38;5;124mensure_2d[39m[38;5;124m"[39m, [38;5;28;01mTrue[39;00m):
[0;32m--> 588[0m     [38;5;28mself[39m[38;5;241m.[39m_check_n_features(X, reset[38;5;241m=[39mreset)
[1;32m    590[0m [38;5;28;01mreturn[39;00m out

File [0;32m~/anaconda3/lib/python3.11/site-packages/sklearn/base.py:389[0m, in [0;36mBaseEstimator._check_n_features[0;34m(self, X, reset)[0m
[1;32m    386[0m     [38;5;28;01mreturn[39;00m
[1;32m    388[0m [38;5;28;01mif[39;00m n_features [38;5;241m!=[39m [38;5;28mself[39m[38;5;241m.[39mn_features_in_:
[0;32m--> 389[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[1;32m    390[0m         [38;5;124mf[39m[38;5;124m"[39m[38;5;124mX has [39m[38;5;132;01m{[39;00mn_features[38;5;132;01m}[39;00m[38;5;124m features, but [39m[38;5;132;01m{[39;00m[38;5;28mself[39m[38;5;241m.[39m[38;5;18m__class__[39m[38;5;241m.[39m[38;5;18m__name__[39m[38;5;132;01m}[39;00m[38;5;124m [39m[38;5;124m"[39m
[1;32m    391[0m         [38;5;124mf[39m[38;5;124m"[39m[38;5;124mis expecting [39m[38;5;132;01m{[39;00m[38;5;28mself[39m[38;5;241m.[39mn_features_in_[38;5;132;01m}[39;00m[38;5;124m features as input.[39m[38;5;124m"[39m
[1;32m    392[0m     )

[0;31mValueError[0m: X has 3458 features, but RandomForestClassifier is expecting 3679 features as input.

